route:
  receiver: default
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 3h

receivers:
- name: default
  slack_configs:
  - api_url: ${ALERTMANAGER_SLACK_WEBHOOK_URL}
    channel: "#alerts"
    send_resolved: true
