name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  compose-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate docker-compose
        uses: hoverkraft-tech/compose-action@v2
        with:
          compose-file: docker-compose.yml
